# Default values for metadata-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

logLevel: DEBUG

image:
  pullPolicy: IfNotPresent
  registry: ""
  name: sds/metadata-submitter
  tag: 0.13.1

mongo:
  create: true
  image:
    pullPolicy: IfNotPresent
    name: mongo
    tag: 4.2.3
  storageClass: cinder
  storage: 100Mi

dbConnection:
  hostname: mongo
  port: 27017
  username: "" # If username is left empty, random username will be used
  password: "" # If password is left empty, random password will be used

ingress:
  create: true
  tls: true
  certSecret: ""    # Name of the secret containing certificates. Required if ingress.create and ingress.tls set to true
  hostname: ""

auth:
  url: ""
  redirect: ""
  oidc: ""
  id: ""
  secret: ""

doi:
  api: https://api.test.datacite.org/dois
  prefix: ""
  user: ""
  key: ""
  discovery: ""

metax:
  user: ""
  pass: ""
  url: ""
