# Default values for metadata-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

logLevel: DEBUG

image:
  pullPolicy: IfNotPresent
  registry: ""
  name: cscfi/metadata-submitter
  tag: v0.7.1

mongo:
  create: true
  hostname: mongo-metadata-submitter
  port: 27017
  image:
    pullPolicy: IfNotPresent
    name: mongo
    tag: 4.2.3
  storageClass: ""
  storage: 100Mi
  username: "" # If username is left empty, random username will be used
  password: "" # If password is left empty, random password will be used

ingress:
  create: true
  tls: false
  certSecret: ""    # Name of the secret containing certificates. Required if ingress.create and ingress.tls set to true
  hostname: localhost

auth:
  idpReferer: ""
  jwk: ""
  url: ""
  oidc: ""
