{{- if not .Values.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-aai
type: Opaque
data:
  id: {{ .Values.auth.id | b64enc }}
  secret: {{ .Values.auth.secret | b64enc }}
{{- end }}
