{{- if not .Values.vaultSecrets }}
apiVersion: v1
data:
{{- if .Values.dbConnection.password }}
  INITDB_ROOT_PASSWORD: {{ .Values.dbConnection.password | b64enc }}
{{- else }}
  INITDB_ROOT_PASSWORD: {{ randAlphaNum 20 | b64enc }}
{{- end }}
{{- if .Values.dbConnection.username }}
  INITDB_ROOT_USERNAME: {{ .Values.dbConnection.username | b64enc }}
{{- else }}
  INITDB_ROOT_USERNAME: {{ randAlphaNum 10 | b64enc }}
{{- end }}
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-db
type: Opaque
{{- end }}
