apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sda.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "sda.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "sda.fullname" . }}
      annotations:
        {{- if not .Values.vaultSecrets }}
        checksum/secret: {{ include (print $.Template.BasePath "/db-secret.yaml") . | sha256sum }}
        {{- end }}
{{- if .Values.podAnnotations }}
{{- toYaml .Values.podAnnotations | nindent 8 -}}
{{- end }}
    spec:
      serviceAccountName: metadata
      containers:
      - name: {{ template "sda.fullname" . }}
        image: {{ template "image.registry" . }}{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.command }}
        command:
{{- toYaml .Values.command | nindent 8 -}}
{{- end }}
        securityContext:
          allowPrivilegeEscalation: false
        # prevents pod from running
        # command: ["sh", "-c", "tail -f /dev/null"]
        env:
        {{- if not .Values.vaultSecrets }}
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-db
              key: INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-db
              key: INITDB_ROOT_PASSWORD
        {{- end }}
        - name: MONGODB_HOST
          value: "{{ .Values.dbConnection.hostname }}:{{ .Values.dbConnection.port }}"
        - name: BASE_URL
          value: "{{ .Values.auth.url }}"
        - name: REDIRECT_URL
          value: "{{ .Values.auth.redirect }}"
        - name: OIDC_URL
          value: "{{ .Values.auth.oidc }}"
        {{- if not .Values.vaultSecrets }}
        - name: AAI_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-aai
              key: secret
        - name: AAI_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-aai
              key: id
        {{- end }}
        - name: LOG_LEVEL
          value: "{{ .Values.logLevel }}"
        - name: DOI_API
          value: "{{ .Values.doi.api }}"
        - name: DOI_PREFIX
          value: "{{ .Values.doi.prefix }}"
        - name: DOI_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-doi
              key: user
        - name: DOI_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-doi
              key: key
        - name: DOI_DISCOVERY
          value: "{{ .Values.doi.discovery }}"
        - name: METAX_URL
          value: "{{ .Values.metax.url }}"
        - name: METAX_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-metax
              key: user
        - name: METAX_PASS
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-metax
              key: password
        ports:
        - name: webapp
          containerPort: 5430
        volumeMounts:
        - name: tmp
          mountPath: "/tmp"
        - mountPath: /app/private
          name: private
        - mountPath: /app/static
          name: static
      volumes:
      - name: tmp
        emptyDir: {}
      - name: static
        emptyDir: {}
      - name: private
        emptyDir: {}
