{{- if not .Values.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-doi
type: Opaque
data:
  user: {{ .Values.doi.user | b64enc }}
  key: {{ .Values.doi.key | b64enc }}
{{- end }}
