---
{{- if .Values.ingress.create }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "sda.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- if .Values.ingress.issuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "sda.fullname" . }}
          servicePort: 5430
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ if .Values.ingress.certSecret }}{{ .Values.ingress.certSecret }}{{- else }}"{{ template "sda.fullname" . }}-ingress-metadata"{{- end }}
  {{- end }}
{{- end }}
