---
{{ if .Values.ingress.create }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "sda.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "sda.fullname" . }}
              servicePort: 5430
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ template "sda.fullname" . }}-expose
  {{- end }}
{{- end }}
