{{- if not .Values.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-metax
type: Opaque
data:
  user: {{ .Values.metax.user | b64enc }}
  password: {{ .Values.metax.pass | b64enc }}
{{- end }}
