{{- if .Values.mongo.create }}
apiVersion: v1
kind: Service
metadata:
  name: mongo-{{ template "sda.fullname" . }}
  labels:
    app: mongo-{{ template "sda.fullname" . }}
spec:
  ports:
  - port: {{ .Values.mongo.port }}
    protocol: TCP
    targetPort: {{ .Values.mongo.port }}
  selector:
    app: mongo-{{ template "sda.fullname" . }}
{{- end }}
