---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sda.fullname" . }}
  labels:
    app: {{ template "sda.fullname" . }}
spec:
  ports:
  - name: webapp
    port: 5430
    targetPort: webapp
    protocol: TCP
  selector:
    app: {{ template "sda.fullname" . }}
